[server]
headless = true
enableCORS = false
port = 8501

[theme]
base="dark"
primaryColor="#f63366"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#ffffff"
font="sans serif"
